[package]
name = "remake2048"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.3.0"
colored = "2.0.0"
rand = "0.8.5"
vector2d = "2.2.0"
